### ISSUE TITLE
Removing hardcoded text from day 1.

### ISSUE THREAD

**Issue by Antes** [Archer70/CoreStore#10]
This is something bothers me actually :P While the project at its early days, we should be doing everything right. So I think its best we load a CoreShop language file across whole project at start, if this file gets too big we split it which I assume it will happen once we get final release (note; I only expect CoreShop & CoreShopAdmin language files to exist).

**Comment by Archer70** [comment]
Quite right. That was on my ToDo list in the next few days. Thanks for taking the initiative!

**Comment by Archer70** [comment]
Gonna go ahead and move this to Done, since you took out all the hard coded text, aside from placeholders.
