### ISSUE TITLE
Uninstall cannot remove hooks.

### ISSUE THREAD

**Issue by Antes** [Archer70/CoreStore#11]
<s>I encountered this on uninstall, it keeps 4 hook as is and creating error in forum.</s>

Actually it seems you need to tick the database part to remove the hooks. This should not be optional and needs to be separated from the actual data remover (which eventually happen in shop).

**Comment by Archer70** [comment]
Could of sworn I commented on this earlier.  I'll look into this as soon as I get back. Thanks for pointing it out.

**Comment by Archer70** [comment]
Technically this is a database operation, so it could be argued that it does belong with data removal. Plus I could see a possible reason to want to uninstall the files but not the hooks.

I'll ask Oldiesmann's opinion later, but I'm leaning toward leaving hooks where they are.

**Comment by Antes** [comment]
If you leave hooks behind, it creates errors in log. If you move forward with that option you also remove the actual data we store related to modification. Which is not something we like to do.

**Comment by Archer70** [comment]
Fair enough. I believe it's possible to add and remove hooks via package-info.xml, but that feature isn't documented so it'll take some research to implement.
