### ISSUE TITLE
Default Theme fallback

### ISSUE THREAD

**Issue by XinYenFon** [Archer70/CoreStore#25]
While testing Lunarfall, i also had CoreStore on the same install, decided to give it a shot so I can see how it plays with other themes, turns out you can't use CoreStore if its template not copied over to themes. If I'm not mistaken, it should fallback to default theme.

a bug? a feature? or something else?

**Comment by Archer70** [comment]
That would be a bug I think. I'll look into it, thanks.

**Comment by Antes** [comment]
A quick test.
